source 'https://rubygems.org'

gem 'rails'
gem 'sqlite3'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'bcrypt-ruby', '~> 3.1.5', require: "bcrypt"
gem "paperclip", "~> 4.2"
gem 'bootstrap-sass', '~> 3.3.4'
gem 'haml'
gem 'hirb'


group :development do
  gem 'byebug'
  gem 'web-console'
  gem 'spring'
  gem 'quiet_assets'
end

group :test, :development do
  gem 'rspec-rails'
  gem 'pry'
end

group :test do
  gem 'shoulda-matchers'
  gem 'capybara'
end
